run:
  tests: false

linters-settings:
  lll:
    line-length: 110
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
#      - ifElseChain
      - octalLiteral
      - wrapperFunc
      - commentFormatting
      - unnamedResult

linters:
  disable-all: true
  enable:
    - gocritic
    - errcheck
    - ineffassign
    - gas
    - gofmt
    - golint
    - gosimple
    - govet
    - lll
    - varcheck
    - unused
    - bodyclose

issues:
  exclude-rules:
    - linters:
        - gosec
      text: "G404: "
