name: Test LemonDB

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      ## this will contain a matrix of all of the combinations
      ## we wish to test again:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest, macos-latest]

    ## Defines the platform for each test run
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test -race -v ./...